name = "sat-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
# Soft / hard TTL minutes (documented in README)
SOFT_TTL_MINUTES = "120"
HARD_TTL_MINUTES = "720"

[[kv_namespaces]]
binding = "TLE_KV"
id = "14236d7044d745108861e3c2b889f564"
preview_id = "1f55c65be925448ba56224fd1c0f167d"

[triggers]
crons = ["0 */4 * * *"]

[observability]
enabled = true
